# Parameter file for joystick

joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:  
      x: 1      # Left thumb stick vertical
    scale_linear: 
      x: 0.5    # regular speed 0.5 m/s
    scale_linear_turbo:
      x: 1.0    # turbo speed 1 m/s

    axis_angular:  
      yaw: 0    # Left thumb stick horizontal
    scale_angular: 
      yaw: 1.0  # regular speed 1 rad/s
    scale_angular_turbo: 
      yaw: 2.0  # turbo speed 2 rad/s

    require_enable_button: true
    enable_button: 4  # Left shoulder button: dead man switch for regular speed
    enable_turbo_button: 5  # Right shoulder button: dead man switch for turbo speed